apiVersion: v1
kind: ConfigMap
metadata:
  name: detector-config
  namespace: sentinel
data:
  SENTINEL_PROMETHEUS_URL: "http://kps-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
  SENTINEL_PROJECT_ID: "cost-sentinel-13402"
  SENTINEL_BIGQUERY_DATASET: "billing_export"
  SENTINEL_BILLING_TABLE: "gcp_billing_export_v1_*"
  SENTINEL_IDLE_CPU_THRESHOLD: "0.10"
